sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: y2FoSsdl9IPFF3ioMkqIQz9evdTJ61yuOKaL22WIILiOCgxCKz0eqkLCSeMDIzEBJdKaNIH8onAIQKZXJBK3uLijb0OAb14ykmQJoant31sm2v5+TFFejmCbJBdTvDfp4m8l2Z/Uf5E7Gg/qoIHqfCtU7dwTp64hfOV4fdIEovt3cHoeMSOeTTBAapvrAmtvdatstRg2QjESA/yYmq4kDicyXNCvlCiNhX7NfO8zEyF6fmRWK99BoP1B6IPIJB4t1EY7KVrJizQhOEiqcPzHflL+NKwxf/Px7d0nXu8i7HQtl76qnQ9OUogTcnpPBGaXX+1+cRC9mvI61G1jtv4sFIR/SEQ3YLxAVTbb3canuti8KJG1BEGeO5dQa3aUysXw0AkS+4WFku/6VC8l1ZJoh72xgPuy1tjHiRyPKIQgxj9xDapImAl9PpzbcKjZjWl2Y6o74tZBl6CxvrWN/Ul5TiHu67KVQzfyYakC7HjXMJ1/+c1pwPm3arB4zGbVTSOH52LGv0XnaOmOYG044RaeN/W19XG6YlyGanxhgCBMBxT8XyDYMErQw+b5fHBLqfr8IE7+A+UtzFBJcxR9NNaRbGU7K8XQwoPxZJxPO7M1wvoNDBrvDPyo8j/h+kVEyqUnQbZP1h6RFTLdUAD2kRFSX0ootoLzRoRNQIHcPwIE9m0=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: VQviN01I34OIYwHQmm29Dyvuk2kuwSCRqlAzUIue3l+o50r5DD95WVd21EZmboowQKk9Cm8CNIIvgkg66vbrMNvy090SqWixWXb+Mus5cVg+kgyNRGYJmLVqQxrYYXCYxK/qCUZWwAqWRnEy6Lnir0/A5q0ZoRdHLub00IAYrNrvyY4t3Q4QtXbpHg9P5tj6B0ePD8fkfu/oKRz6E98pHLLTBm90DqMTD9JsYFFsGDSzwW9gHDnyfIB5xkUwFR/GrCMiG8YFVh+mYuS1oLtGtJjR0JBmFRPNeWt1hBz9CEtFFiRfuQcwXLi/zEPUiMrtq9sna/856QJ95TuZyOgMi8vHWRUoidSQRgeUuFyTs9JhZcvkqhEYuQdfLjmzIzW2jVQbjMP939diDANmtAtlxpOJWF5N6HAEULUVEG29emBkRVu4lXHQX5X+0ps7r6dX8Jcl1vqu7BaPiujabe3XeWi7lHhH57FhXPem2DgE0WaylCeVTMXDCcAlTtkp8CR+ke6/9Ml5ks3rzqHTE759zvJx4ql4SCR5GFcS0c6zEifOVRi1h6ooMnWWyDGzLfBUYkTM0b34Q82vpIPbr4+tmnxK8qDU6KN3jMwmr+Wg88NH1/dAZoQkR9Wu49QLpdLsRLL8D/yYVS249sQujfBxxjxeNF384Vq5sunCB7RWmlQ=
